import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Modalprovider } from "@/components/modal-provider";
import { CrispProvider } from "@/components/crispprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Creatix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <CrispProvider/>
        <body className={inter.className}>
          <Modalprovider/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
